/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	// enable GPIOA clock
	RCC->AHB1ENR |= (1<<0);

	// GPIO settings
	GPIOA->MODER |= (1<<10); // general output type

	GPIOA->PUPDR |= (2<<10); // pull down

	int i;

	while(1){

		// blink led
		GPIOA->ODR |= (1<<5);
		for(i=1000000; i; i--);

		GPIOA->ODR &= ~(1<<5);
		for(i=0; i<1000000; i++);

	}
	return 0;
}
